# Site
repository: taeckyung/taeckyung.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Taeckyung Lee
title: Ph.D. Candidate, KAIST
email: taeckyung@kaist.ac.kr
# email_title: Email (Email title override)
phone: 
# phone_title: Phone (Phone title override)
website: 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: taeckyung_lee
github_username:  taeckyung
stackoverflow_username: 
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: taeckyung
xing_username: 
pinterest_username: 
youtube_username: 
orcid_username: 
googlescholar_username: RKaOmicAAAAJ

# Additional icon links
additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
gtag: G-R2EM4J3E8J
description: "Taeckyung (TK) Lee â€” Ph.D. candidate at KAIST NMSL. Research on adaptation, mobile AI, and personalization. Works include BiTTA (ICML 2025), AETTA (CVPR 2024), SoTTA (NeurIPS 2023). Also known as Taeckyung Lee, TK Lee, Taekyung Lee, v-taeclee."

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate at <a href="https://nmsl.kaist.ac.kr" target="_blank">KAIST NMSL</a>, under the guidance of <a href="https://sites.google.com/site/wewantsj/" target="_blank">Prof. Sung-Ju Lee</a>, with close collaboration with <a href="https://alinlab.kaist.ac.kr/shin.html" target="_blank">Prof. Jinwoo Shin</a> and <a href="https://taesikgong.com" target="_blank">Prof. Taesik Gong</a>. I earned my M.S. in Electrical Engineering from KAIST, also under the supervision of <a href="https://sites.google.com/site/wewantsj/" target="_blank">Prof. Sung-Ju Lee</a>. I completed my B.S. in Computing at KAIST, graduating Magna Cum Laude.
  
  My research interests include machine learning for end users, including mobile AI, model adaptation, and personalization. I am currently focusing on model adaptation in inference time (test-time adaptation). 
  My recent work includes "BiTTA" (ICML 2025), "AETTA" (CVPR 2024), and "SoTTA" (NeurIPS 2023), which focus on (1) RL-inspired adaptation with a few user feedback,
  (2) estimating adaptation performance without labeled data, and (3) adaptation with challenging noisy data streams, emphasizing the robustness and reliability of test-time adaptation.
  
# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  # - title: Experience
  #   layout: list
  #   content:
  #     - layout: right
  #       title: Company name
  #       sub_title: Job title
  #       caption: Date Range (eg. November 2016 - present)
  #       link: Link to company (optional)
  #       quote: >
  #         Short description of the company (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description of role


  - title: Latest News
    layout: text
    content: |
      **Jul 2025**  Research intern at Microsoft Research Asia (Advisor: [Lili Qiu](https://www.microsoft.com/en-us/research/people/liliqiu/)).
      <br>**Jun 2025**  Recognized as an Outstanding Reviewer at CVPR '25 (Top-5.6%).
      <br>**May 2025**  First-author paper (BiTTA) accepted at ICML '25 (Acceptance rate: 26.9%).
      <br>**May 2025**  First-author paper (CrashSniffer) accepted at MobiSys Workshop (EnvSys) '25.
      <br>**May 2025**  Invited talk at UNIST UAI lab.
      <br>**Feb 2024**  First-author paper (AETTA) accepted at CVPR '24 (Acceptance rate: 23.6%).
      <br>**Sep 2023**  Co-first-author paper (SoTTA) accepted at NeurIPS '23 (Acceptance rate: 26.1%).
      <br>**Jun 2022**  First-author paper (PAFE) accepted at CVPR Workshop (CVPM) '22.
      <br>**Jun 2022**  Demo at MobiSys '22.
      <br>**Oct 2020**  Selected as a scholarship recipient of the Kwon Yong-se Scholarship (KAIST EE).


  - title: Education
    layout: list
    content:
      - layout: top
        title: Ph.D. Candidate, KAIST
        sub_title: Ph.D. Candidate in School of Electrical Engineering (Advisor&#58; <a href="https://sites.google.com/site/wewantsj/" target="_blank"><b>Prof. Sung-Ju Lee</b></a>)
        caption: 2022.08 - Present
    
      - layout: top
        title: M.S., KAIST
        sub_title: M.S. in School of Electrical Engineering (Advisor&#58; <a href="https://sites.google.com/site/wewantsj/" target="_blank"><b>Prof. Sung-Ju Lee</b></a>)
        caption: 2020.08 - 2022.08
          
      - layout: top
        title: B.S., KAIST
        sub_title: B.S. in School of Computing
        description: |
          - GPA 3.96/4.30 (Magna Cum Laude), Advanced Major, Certificate in AI
        caption: 2016.02 - 2020.08

  - title: Preprints # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      # - layout: top
      #   title: Conferences and Journals
      - layout: top
        title: "<a href=\"https://arxiv.org/abs/2510.20853\" target=\"_blank\">\"Beyond Hearing: Learning Task-agnostic ExG Representations from Earphones via Physiology-informed Tokenization
\"</a>"
        additional_links:
          - title:  Paper
            icon: fas fa-file-pdf
            url: https://arxiv.org/abs/2510.20853
        description: |
          Hyungjun Yoon, Seungjoo Lee, Yu Yvonne Wu, Xiaomeng Chen, Taiting Lu, Freddy Yifei Liu, <b>Taeckyung Lee</b>, Hyeongheon Cha, Haochen Zhao, Gaoteng Zhao, Sung-Ju Lee, Cecilia Mascolo, Dongyao Chen, Lili Qiu

          **Preprint**

  - title: Conference Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      # - layout: top
      #   title: Conferences and Journals
      - layout: top
        title: "<a href=\"https://arxiv.org/abs/2505.18514\" target=\"_blank\">\"Test-Time Adaptation with Binary Feedback\" (BiTTA)</a>"
        additional_links:
          - title:  Project page
            icon: fas fa-home
            url: https://nmsl.kaist.ac.kr/projects/bitta/
          - title:  Paper
            icon: fas fa-file-pdf
            url: https://arxiv.org/abs/2505.18514
          - title:  Code
            icon: fab fa-github
            url: https://github.com/taeckyung/BiTTA
        description: |
          <b>Taeckyung Lee</b>, Sorn Chottananurak, Junsu Kim, Jinwoo Shin, Taesik Gong^, Sung-Ju Lee^

          **ICML 2025** (^: Equal advising. Acceptance rate: 26.9%)


      - layout: top
        title: "<a href=\"https://arxiv.org/pdf/2404.01351.pdf\" target=\"_blank\" onclick=\"captureOutboundLink(https://arxiv.org/pdf/2404.01351.pdf); return false;\">\"AETTA: Label-Free Accuracy Estimation for Test-Time Adaptation\"</a>"
        additional_links:
          - title:  Project page
            icon: fas fa-home
            url: https://nmsl.kaist.ac.kr/projects/aetta/
          - title:  Paper
            icon: fas fa-file-pdf
            url: https://arxiv.org/pdf/2404.01351.pdf
          - title:  Code
            icon: fab fa-github
            url: https://github.com/taeckyung/AETTA
          - title: Video
            icon: fa fa-youtube-play
            url: https://www.youtube.com/watch?v=qZJ_0-rxMs0
        description: | 
          <b>Taeckyung Lee</b>, Sorn Chottananurak, Taesik Gong, Sung-Ju Lee
          
          **CVPR 2024** (Acceptance rate: 23.6%)

      - layout: top
        title: "<a href=\"https://proceedings.neurips.cc/paper_files/paper/2023/file/2da53cd1abdae59150e35f4693834f32-Paper-Conference.pdf\" target=\"_blank\">\"SoTTA: Robust Test-Time Adaptation on Noisy Data Streams\"</a>"
        additional_links:
          - title:  Project page
            icon: fas fa-home
            url: https://nmsl.kaist.ac.kr/projects/sotta/
          - title:  Paper
            icon: fas fa-file-pdf
            url: https://proceedings.neurips.cc/paper_files/paper/2023/file/2da53cd1abdae59150e35f4693834f32-Paper-Conference.pdf
          - title:  Code
            icon: fab fa-github
            url: https://github.com/taeckyung/SoTTA
          - title:  Video
            icon: fa fa-youtube-play
            url: https://neurips.cc/virtual/2023/poster/72892
        description: | 
          Taesik Gong\*, Yewon Kim\*, <b>Taeckyung Lee&#42;</b>, Sorn Chottananurak, Sung-Ju Lee
          
          **NeurIPS 2023** (&#42; Co-first author. Acceptance rate: 26.1%)


    
  - title: Workshop Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: top
        title: "<a>\"CrashSniffer: UWB-Based Anchor-Free Pedestrian Collision Prediction for Personal Mobility Vehicles\"</a>"
        description: |
          <b>Taeckyung Lee</b>, Juseung Lee, Ryuhaerang Choi, Seungjoo Lee, Hyeongheon Cha, Hyungjun Yoon, Song Min Kim, Sangwook Bak, Sung-Ju Lee. 

          **MobiSys Workshops (EnvSys) 2025** (Oral presentation, peer-reviewed, archived)

      - layout: top
        title: "<a href=\"https://openaccess.thecvf.com/content/CVPR2022W/CVPM/papers/Lee_Predicting_Mind-Wandering_With_Facial_Videos_in_Online_Lectures_CVPRW_2022_paper.pdf\" target=\"_blank\">\"Predicting Mind-Wandering with Facial Videos in Online Lectures\"</a>"
        additional_links:
          - title:  Project page
            icon: fas fa-home
            url: https://nmsl.kaist.ac.kr/projects/attention/
          - title:  Paper
            icon: fas fa-file-pdf
            url: https://openaccess.thecvf.com/content/CVPR2022W/CVPM/papers/Lee_Predicting_Mind-Wandering_With_Facial_Videos_in_Online_Lectures_CVPRW_2022_paper.pdf
        description: | 
          <b>Taeckyung Lee</b>, Dain Kim, Sooyoung Park, Dongwhi Kim, Sung-Ju Lee

          **CVPR Workshops (CVPM) 2022** (Oral presentation, peer-reviewed, archived)

          - Also appeared at **MobiSys 2022 Demo**

  - title: Work Experiences
    layout: list
    content:
      - layout: top
        title: Microsoft Research Asia
        sub_title: Research Intern (Advisor&#58; <a href="https://www.microsoft.com/en-us/research/people/liliqiu">Lili Qiu</a>)
        caption: 2025.07 - 2025.12 (expected)
      - layout: top
        title: Networking and Mobile Systems Lab, KAIST
        sub_title: Research Assistant
        caption: 2020.03 - Present
      - layout: top
        title: Advanced Networking Lab, KAIST
        sub_title: Undergraduate Researcher
        caption: 2019.03 - 2019.12

  - title: Honors
    layout: list
    content:
      - layout: top
        title: Outstanding Reviewer
        sub_title: CVPR 2025 (<i>Top-5.6% among all reviewers</i>)
        caption: 2025.06.13
      - layout: top
        title: Kwon Young-se Scholarship
        sub_title: School of EE, KAIST (<i>Top-2 among EE grad school applicants in 2020 Fall</i>)
        caption: 2020.10.12
      - layout: top
        title: The National Scholarship for Science and Engineering
        sub_title: Ministry of Science and ICT, Korean Government (<i>In acknowledgment of a high GPA</i>)
        caption: 2018.08.10

  - title: Professional Services
    layout: list
    content:
      - layout: top
        title: Journal Reviewer
        description: |
          - TMLR
      - layout: top
        title: Conference Reviewer
        description: |
          - NeurIPS '24, '25
          - ICML '25
          - ICLR '25
          - CVPR '24, '25, '26
          - ICCV '25
          - AAAI '26
          - WACV '25
      - layout: top
        title: Workshop Reviewer
        description: |
          - 2nd Workshop on Test-Time Adaptation (PUT) @ ICML '25

  - title: Teaching Experiences
    layout: list
    content:
      - layout: top
        title: Teaching Assistant, KAIST
        description: |
          - EE209 Programming Structures for EE (Spring 2025 (Head TA), Fall 2024, Spring 2023 (Head TA), Fall 2021 (Head TA))
          - EE323 Computer Networks (Spring 2024, Spring 2022, Spring 2021)
          - EE415 Operating Systems and System Programming for EE (Fall 2023)
          - EE595 Mobile Computing, Sensing, Learning, and Interactions (Fall 2022)
          - CS496 Immersion Camp (Summer 2019)

  - title: Patents
    layout: list
    content:
      - layout: top
        title: UWB-based Pedestrian Collision Avoidance System for Personal Mobility Devices
        description: |
          Sung-Ju Lee, <b>Taeckyung Lee</b>, Hyungjun Yoon, Seungjoo Lee, Hyeongheon Cha
          
          *Korea Patent; Date of patent: 2025.11.06, No.10-2025-0166592, Filing date: 2025.02.12, No.10-2025-0018095*

    
      - layout: top
        title: Time-Aware Reinforcement-Learning Method for Geographic Ad Hoc Routing with Pre-defined Mobility
        description: |
          Jaeha Ahn, Sung-Ju Lee, Taesik Gong, Hyungjun Yoon, <b>Taeckyung Lee</b>

          *Korea Patent; Date of patent: 2024.12.02, No.10-2738891, Filing date: 2022.11.11, No.10-2022-0150662*
      - layout: top
        title: Reinforcement Learning for Ad-hoc Routing Using Pre-defined Mobility
        description: |
          Sung-Ju Lee, Taesik Gong, Hyungjun Yoon, <b>Taeckyung Lee</b>, Jaeha Ahn

          *Korea Patent; Date of patent: 2024.04.22, No.10-2660836, Filing date: 2022.03.21, No.10-2022-0034824*

  - title: Miscellaneous
    layout: list
    content: 
      - layout: top
        title: E-Sports
        description: |
          As a previous enthusiastic e-sports player, I am also interested in human factors in e-sports.
          
          Analysis on Personality and In-Game Factors in League of Legends (<a href="https://github.com/taeckyung/CS564-LoL-Personality/blob/master/Analysis%20on%20Personality%20and%20In-Game%20Factors%20in%20League%20of%20Legends.pdf" target="_blank">Link</a>)

          - I conducted an in-depth analysis of the personalities and in-game factors of League of Legends players through a collaborative survey with the Professional Spectator YouTube channel.
          
          Few records as a player&#58;
          
          - Top 0.1% Player (Master tier) in KR Server, League of Legends (2020)
          - Champion in Daejeon Metropolitan City, International e-Sports Festival (IEF), League of Legends (2019)
          - Top-500 Player in KR Server, Overwatch (2017)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
